import type { GeneratorConfig } from '../../types/index.js';

/**
 * Generates Domain Entity interface with DTOs
 */
export function generateEntity(config: GeneratorConfig): string {
  const { entityName, moduleName, columns } = config;

  const columnFields = columns.map(c => {
    const typeMap: Record<string, string> = {
      'string': 'string',
      'number': 'number',
      'boolean': 'boolean',
      'date': 'string' // ISO string for dates
    };
    return `  ${c.key}: ${typeMap[c.type]};`;
  }).join('\n');

  const createDTOFields = columns
    .filter(c => !['id', 'createdAt', 'updatedAt'].includes(c.key))
    .map(c => {
      const typeMap: Record<string, string> = {
        'string': 'string',
        'number': 'number',
        'boolean': 'boolean',
        'date': 'string'
      };
      return `  ${c.key}: ${typeMap[c.type]};`;
    }).join('\n');

  return `/**
 * Domain Entity: ${entityName}
 * Generated by shadcn-page-gen
 */
export interface ${entityName} {
  id: string;
${columnFields}
  updatedAt: Date;
}

export interface Create${entityName}DTO {
${createDTOFields || '  // Add your fields here'}
}

export interface Update${entityName}DTO extends Partial<Create${entityName}DTO> {
  id: string;
}
`;
}
