import type { GeneratorConfig } from '../../types/index.js';

/**
 * Generates App Router Page
 */
export function generatePage(config: GeneratorConfig): string {
  const { pageName, moduleName, entityName } = config;

  return `import { Suspense } from 'react';
import { ${entityName}List } from '@/modules/${moduleName}/presentation/components/${moduleName}-list';

/**
 * ${pageName} Page
 * Generated by shadcn-page-gen
 */
export default function ${entityName}Page() {
  return (
    <div className="container mx-auto py-10 space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">${pageName}</h1>
        <p className="text-muted-foreground">
          Manage your ${pageName.toLowerCase()}.
        </p>
      </div>

      <Suspense fallback={<div>Loading...</div>}>
        <${entityName}List />
      </Suspense>
    </div>
  );
}
`;
}
