import type { GeneratorConfig } from '../../types/index.js';

/**
 * Generates Domain Repository Interface
 */
export function generateRepositoryInterface(config: GeneratorConfig): string {
  const { entityName, moduleName } = config;

  return `import { ${entityName}, Create${entityName}DTO, Update${entityName}DTO } from '../entities/${moduleName}.entity';

/**
 * Repository Interface: ${entityName}
 * Generated by shadcn-page-gen
 */
export interface I${entityName}Repository {
  findAll(params?: any): Promise<${entityName}[]>;
  findById(id: string): Promise<${entityName} | null>;
  create(data: Create${entityName}DTO): Promise<${entityName}>;
  update(data: Update${entityName}DTO): Promise<${entityName}>;
  delete(id: string): Promise<void>;
}
`;
}
