import type { GeneratorConfig } from '../../types/index.js';

/**
 * Generates App Router Template for page transitions
 */
export function generateTemplate(config: GeneratorConfig): string {
  const { animations } = config;

  // Get animation config based on intensity
  const getAnimationConfig = () => {
    switch (animations.intensity) {
      case 'subtle':
        return {
          initial: '{ opacity: 0, y: 10 }',
          animate: '{ opacity: 1, y: 0 }',
          transition: '{ duration: 0.2 }'
        };
      case 'bold':
        return {
          initial: '{ opacity: 0, scale: 0.95, y: 30 }',
          animate: '{ opacity: 1, scale: 1, y: 0 }',
          transition: '{ duration: 0.4, ease: [0.43, 0.13, 0.23, 0.96] }'
        };
      default: // moderate
        return {
          initial: '{ opacity: 0, y: 20 }',
          animate: '{ opacity: 1, y: 0 }',
          transition: '{ duration: 0.3, ease: "easeInOut" }'
        };
    }
  };

  const animConfig = getAnimationConfig();

  return `'use client';

import { motion } from 'framer-motion';

/**
 * Page Template with Framer Motion transitions
 * Generated by shadcn-page-gen
 */
export default function Template({ children }: { children: React.ReactNode }) {
  return (
    <motion.div
      initial={${animConfig.initial}}
      animate={${animConfig.animate}}
      exit={{ opacity: 0, y: -20 }}
      transition={${animConfig.transition}}
    >
      {children}
    </motion.div>
  );
}
`; }