import type { GeneratorConfig } from '../../types/index.js';

/**
 * Generates Application Use Case
 */
export function generateUseCase(config: GeneratorConfig): string {
  const { entityName, moduleName } = config;

  return `import { ${entityName} } from '../../domain/entities/${moduleName}.entity';
import { I${entityName}Repository } from '../../domain/repositories/${moduleName}.repository.interface';

/**
 * Use Case: Get ${entityName}s
 * Generated by shadcn-page-gen
 */
export class Get${entityName}sUseCase {
  constructor(private readonly repository: I${entityName}Repository) {}

  async execute(params?: any): Promise<${entityName}[]> {
    return await this.repository.findAll(params);
  }
}
`;
}
